### PR TITLE
SC-196 RemoteXDA Instance Sorting

### PR DESCRIPTION
**Pull request by KulinduC**
Fixed sorting for Remote Meter and Remote Assets. Relies on Gemstone changes: https://github.com/GridProtectionAlliance/gpa-gemstone/pull/308 and OpenXDA changes: https://github.com/GridProtectionAlliance/openXDA/pull/337

### CODE REVIEW

**Comment by KulinduC** [comment]
image
image
image

**Comment by KulinduC** [comment]
image
image
image

**Comment by elwills** [comment]
Fix spelling for `Obfuscated` column (currently `Obsfucated`).

**Review by clackner-gpa — APPROVED** [review]

**Comment by clackner-gpa** [comment]
This is pending an openXDA.Model update

**Pull request merged**
