### PR TITLE
Changed endpoint to use universal cascade delete SC-38

### PR DESCRIPTION
**Pull request by gcsantos-gpa**

### CODE REVIEW

**Review by StephenCWills — CHANGES_REQUESTED** [review]
Wouldn't it make more sense to just replace the `DeleteRecordWhere()` calls with `UniversalCascadeDelete` calls? Or are we worried about performance?

```c#
result += connection.ExecuteNonQuery($"EXEC UniversalCascadeDelete '{meterAssetTable.TableName}', 'MeterID = {meterID} AND AssetID = {assetID}'");
result += connection.ExecuteNonQuery($"EXEC UniversalCascadeDelete '{assetLocationTable.TableName}', 'LocationID = {locationID} AND AssetID = {assetID}'");
```

**Comment by gcsantos-gpa** [comment]
> Wouldn't it make more sense to just replace the `DeleteRecordWhere()` calls with `UniversalCascadeDelete` calls? Or are we worried about performance?
> 
> ```cs
> result += connection.ExecuteNonQuery($"EXEC UniversalCascadeDelete '{meterAssetTable.TableName}', 'MeterID = {meterID} AND AssetID = {assetID}'");
> result += connection.ExecuteNonQuery($"EXEC UniversalCascadeDelete '{assetLocationTable.TableName}', 'LocationID = {locationID} AND AssetID = {assetID}'");
> ```

Is there a call for this directly without using ExecuteNonQuery? Not seeing it in table operations and haven't seen it used before.

**Comment by StephenCWills** [comment]
Your options are `ExecuteNonQuery()` or else something like this...

https://github.com/GridProtectionAlliance/SystemCenter/blob/302876e9e556c5a77c5ae26d27da97c86cbc4e09/Source/Applications/SystemCenter/DataHub.cs#L377-L404

But I didn't mean to say that you should call a `UniversalCascadeDelete()` function. `ExecuteNonQuery()` is fine, but there's no need for the two additional queries or the `foreach` loops.

**Comment by gcsantos-gpa** [comment]
> Your options are `ExecuteNonQuery()` or else something like this...
> 
> https://github.com/GridProtectionAlliance/SystemCenter/blob/302876e9e556c5a77c5ae26d27da97c86cbc4e09/Source/Applications/SystemCenter/DataHub.cs#L377-L404
> 
> But I didn't mean to say that you should call a `UniversalCascadeDelete()` function. `ExecuteNonQuery()` is fine, but there's no need for the two additional queries or the `foreach` loops.

Now that you point this out, it should have been obvious to do it this way from the start. Changed.

**Review by StephenCWills — APPROVED** [review]

**Pull request merged**
